[package]
name = "sysy-cargo-template"
version = "0.1.0"
edition = "2021"

[dependencies]
koopa = "0.0.7"
lalrpop-util = { version = "0.20.2", features = ["lexer"] }

[build-dependencies]
lalrpop = "0.20.2"
